### ISSUE TITLE
Packagist

### ISSUE THREAD

**Issue by jjharr** [minube/Amplitude-PHP#1]
Hey... this looks really useful, but it doesn't seem to be registered with packagist.org so it can't be automatically pulled via composer. Any chance you will register this with packagist.org?

**Comment by fjalvarezdd** [comment]
Hello @jjharr 

Thanks for your interest in our package.

We've just submitted the package to packagist (https://packagist.org/packages/minube/amplitude-php) but please take into account that this is just a development version, we are working on it actually.

Do not hesitate to fork the repo and help us with the development :)

Regards,
